"""Safe delete repetition

Revision ID: d991059254fc
Revises: 417245911e20
Create Date: 2024-11-04 19:39:33.916435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd991059254fc'
down_revision: Union[str, None] = '417245911e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repetition', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repetition', 'deleted')
    # ### end Alembic commands ###
