"""add repetition field to dailynote

Revision ID: f91f8c086bf6
Revises: cccce00e85c1
Create Date: 2024-11-14 15:08:46.768141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91f8c086bf6'
down_revision: Union[str, None] = 'cccce00e85c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
